### PR TITLE
Add support for autopublish attribute

### LINKED ISSUE #62: As a user I can set a boolean value to the autopublish attribute with the rpm_repository module
The pulp_rpm ([3.12](https://github.com/pulp/pulp_rpm/blob/3.13/CHANGES.rst#features-1) [Issue # 7622](https://pulp.plan.io/issues/7622)) plugin added support for ```autopublish``` as a boolean attribute when creating and updating RPM repositories. However, the REST API documentation has not been published/generated since v3.7 and errors out for the [latest](https://pulp-rpm.readthedocs.io/en/latest/restapi.html) tag. The built-in API explorer for pulp does show the new attribute.

### PR DESCRIPTION
**Pull request by ajsween**
This is to add autopublish attribute support for pulp_rpm plugin and addresses issue #62

### CODE REVIEW

**Comment by ajsween** [comment]
Tested against a pulp server container instance (3.13) successfully. Also tested ```ansible-doc pulp.squeezer.rpm_repository``` properly displayed the changes to the documentation block.

**Comment by mdellweg** [comment]
Great addition! Thank you for adding test stanzas to the playbook.
You need to rerecord the fixtures however as described at the end of this section:
https://github.com/pulp/squeezer#testing

basically: 
`make record_rpm_repository`
check that it worked with
`make test_rpm_repository`
and then check in the files generated in the fixtures subdirectory.

**Comment by vkvm** [comment]
I just started using squeezer a couple of days ago and this is one of the first issues I ran into with the `file_repository` module (missing `autopublish`). Though  this is for `rpm_repository`, given the similarities, are the code changes here basically what would be needed for `file_repository` to support `autopublish`?

**Comment by mdellweg** [comment]
>  Though this is for `rpm_repository`, given the similarities, are the code changes here basically what would be needed for `file_repository` to support `autopublish`?

I strongly believe so.

**Comment by ajsween** [comment]
> `make record_rpm_repository`

I'm getting the following error:

```
Created collection for pulp.squeezer at /root/squeezer/pulp-squeezer-0.0.9-dev.tar.gz
ansible-galaxy collection install -p build/collections --.tar.gz --force
usage: ansible-galaxy [-h] [--version] [-v] TYPE ...
ansible-galaxy: error: unrecognized arguments: --.tar.gz
```

**Comment by mdellweg** [comment]
> > `make record_rpm_repository`
> 
> I'm getting the following error:
> 
> ```
> Created collection for pulp.squeezer at /root/squeezer/pulp-squeezer-0.0.9-dev.tar.gz
> ansible-galaxy collection install -p build/collections --.tar.gz --force
> usage: ansible-galaxy [-h] [--version] [-v] TYPE ...
> ansible-galaxy: error: unrecognized arguments: --.tar.gz
> ```

Did you setup a virtual environment for this? You must run make in that environment.
`python -c 'import yaml; print(yaml.safe_load(open("galaxy.yml"))["namespace"])'` should output something useful.

**Comment by mdellweg** [comment]
@ajsween any update on this?

**Comment by ajsween** [comment]
I haven't had time to work on it. I'll see if I can find some time this weekend.

**Comment by mdellweg** [comment]
@ajsween I took the liberty to touch this PR up a bit. Would you mind squashing the commits?

**Pull request merged**
