### PR TITLE
Add Ansible Core 2.13 stable branch to test matrix

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
Time to drop 2.8, huh?

**Comment by mdellweg** [comment]
Let's drop 2.8. It's not passing anymore anyway, and i don't have the time to patch it up.
Will you or should i?

**Comment by evgeni** [comment]
> Will you or should i?

Done, including a cleanup of `Makefile`

**Comment by evgeni** [comment]
hah, now the 2.8 is "expected", but I can't change the config

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
