### PR TITLE
deb_sync: support setting mirror parameter

### PR DESCRIPTION
**Pull request by markgoddard**
Setting mirror=true seems to be necessary to avoid a "Paths are
duplicated" error in some cases.

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]
Nice!

**Comment by markgoddard** [comment]
Do I need to do anything else here?

**Comment by mdellweg** [comment]
Sorry for taking so long. I think this is good. Rerunning CI now...

**Comment by mdellweg** [comment]
Thanks for your patience!

**Comment by markgoddard** [comment]
And thank you for reviewing

**Pull request merged**
