### PR TITLE
Fix ci for python 2.7

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by mdellweg** [comment]
Seriously? Module defaults for collections is now completely broken?

**Comment by evgeni** [comment]
> Seriously? Module defaults for collections is now completely broken?

They ever worked?

**Comment by mdellweg** [comment]
> > Seriously? Module defaults for collections is now completely broken?
> 
> They ever worked?

Module default groups never worked. And i wished for years.

**Comment by mdellweg** [comment]
Maybe related to https://github.com/ansible/ansible/issues/75279

**Comment by mdellweg** [comment]
`for module in $(ls ../../plugins/modules/); do module=${module%.py}; sed -i -e 's/ '${module}':/ pulp.squeezer.'${module}':/' *.yaml; done`
`sed -i -e '/ collections:/,+1d' *.yaml`

**Review by evgeni — APPROVED** [review]

**Pull request merged**
