### PR TITLE
Add remote options

### LINKED ISSUE #55: add client auth options to rpm_remote module
We would like to automate the creation of our RHEL remote repositories. To do this, we need to be able to pass the client cert and key as well as the CA cert.

Pulp API doc: [Create a rpm remote](https://pulp-rpm.readthedocs.io/en/latest/restapi.html#operation/remotes_rpm_rpm_create)

@cognifloyd: Could you help us with this?

### PR DESCRIPTION
**Pull request by mdellweg**
fixes #55

### CODE REVIEW

**Comment by keilr** [comment]
@mdellweg Thanks a lot for your PR. Amazing work!

My test setup:
- rhel8
- pulp/pulp:3.12 container image (and podman)
- ansible 2.10.9

Playbook:
```
- name: get entitlement cert
  slurp:
    src: /etc/pki/entitlement/123456789.pem
  register: entitlement_pem

- name: get entitlement key
  slurp:
    src: /etc/pki/entitlement/123456789-key.pem
  register: entitlement_key

- name: get redhat ca
  slurp:
    src: /etc/rhsm/ca/redhat-uep.pem
  register: redhat_ca

- name: create remote repos
  pulp.squeezer.rpm_remote:
    pulp_url: http://localhost:8080
    username: admin
    password: password
    name: rhel-7-server-rpms
    url: "https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os"
    proxy_url: "{{ pulp3_https_proxy }}"
    ca_cert: "{{ redhat_ca.content | b64decode }}"
    client_cert: "{{ entitlement_pem.content | b64decode }}"
    client_key: "{{ entitlement_key.content | b64decode }}"
    state: present

- name: create a rpm repository
  pulp.squeezer.rpm_repository:
    pulp_url: http://localhost:8080
    username: admin
    password: password
    name: test-rhel7-base
    state: present

- name: sync rpm remote into repository
  pulp.squeezer.rpm_sync:
    pulp_url: http://localhost:8080
    username: admin
    password: password
    repository: test-rhel7-base
    remote: rhel-7-server-rpms
```

Result:
- remote repository was successfully created and starting a repository sync worked as well. The sync cancelled after a while, but this seems to be another issue.
- running the playbook for the second time results in an error (see traceback)
- I had to enable sha1 checksums by adjusting [ALLOWED_CONTENT_CHECKSUMS](https://docs.pulpproject.org/pulpcore/settings.html#allowed-content-checksums). I assume this is an issue on rh-repo side, not pulp or pulp.squeezer related.

```
The full traceback is:
Traceback (most recent call last):

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeezer/plugins/modules/rpm_remote.py", line 131, in main

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/pulp.py", line 241, in process
    self.update()

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/pulp.py", line 195, in update
    self._update_id, parameters=self.primary_key, body=self.entity

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/openapi.py", line 253, in call
    method, url, data=data, headers=headers, unix_socket=self.unix_socket

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible/module_utils/urls.py", line 1304, in open
    return urllib_request.urlopen(request, None, timeout)

  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)

  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)

  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)

  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)

  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)

  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

urllib.error.HTTPError: HTTP Error 400: Bad Request
fatal: [pulp]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": "-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----\n",
            "client_cert": "-----BEGIN CERTIFICATE------...-----END CERTIFICATE-----\n-----BEGIN ENTITLEMENT DATA-----...-----END ENTITLEMENT DATA-----\n-----BEGIN RSA SIGNATURE-----...-----END RSA SIGNATURE-----\n",
            "client_key": "-----BEGIN RSA PRIVATE KEY-----...-----END RSA PRIVATE KEY-----\n",
            "download_concurrency": null,
            "name": "rhel-7-server-rpms",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "policy": null,
            "proxy_password": null,
            "proxy_url": "http://dmz-gate.zrh.local:8080",
            "proxy_username": null,
            "pulp_url": "http://localhost:8080",
            "refresh_api_cache": false,
            "remote_password": null,
            "remote_username": null,
            "state": "present",
            "tls_validation": null,
            "url": "https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os",
            "username": "admin",
            "validate_certs": true
        }
    },
    "msg": "HTTP Error 400: Bad Request"
}
```

```
$ podman logs --tail pulp
...output omitted...
pulp [bc136f6661ae457093d0e34440df4fc7]: django.request:WARNING: Bad Request: /pulp/api/v3/remotes/rpm/rpm/cabf838f-9f29-49f0-ac0c-60573b0a1800/
```

Should I use latest docker image of pulp or is 3.12 ok? Iatest seems to be broken, I wasn't able to connect to the pulp api.

Idempotence: I assume the task result is always `changed: true` while using the  `client_key` option. What about an extra option called something like `client_auth_update: yes/no`? Or add an example on how to check if remote repo exists and then omit the client_key` option.

Let me know if I can help you further with testing, I'm happy to help!

**Comment by keilr** [comment]
@mdellweg Thanks a lot for your PR. Amazing work!

My test setup:
- rhel8
- pulp/pulp:3.12 container image (and podman)
- ansible 2.10.9

Playbook:
```
- name: get entitlement cert
  slurp:
    src: /etc/pki/entitlement/123456789.pem
  register: entitlement_pem

- name: get entitlement key
  slurp:
    src: /etc/pki/entitlement/123456789-key.pem
  register: entitlement_key

- name: get redhat ca
  slurp:
    src: /etc/rhsm/ca/redhat-uep.pem
  register: redhat_ca

- name: create remote repos
  pulp.squeezer.rpm_remote:
    pulp_url: http://localhost:8080
    username: admin
    password: password
    name: rhel-7-server-rpms
    url: "https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os"
    proxy_url: "{{ pulp3_https_proxy }}"
    ca_cert: "{{ redhat_ca.content | b64decode }}"
    client_cert: "{{ entitlement_pem.content | b64decode }}"
    client_key: "{{ entitlement_key.content | b64decode }}"
    state: present

- name: create a rpm repository
  pulp.squeezer.rpm_repository:
    pulp_url: http://localhost:8080
    username: admin
    password: password
    name: test-rhel7-base
    state: present

- name: sync rpm remote into repository
  pulp.squeezer.rpm_sync:
    pulp_url: http://localhost:8080
    username: admin
    password: password
    repository: test-rhel7-base
    remote: rhel-7-server-rpms
```

Result:
- remote repository was successfully created and starting a repository sync worked as well. The sync cancelled after a while, but this seems to be another issue.
- running the playbook for the second time results in an error (see traceback)
- I had to enable sha1 checksums by adjusting [ALLOWED_CONTENT_CHECKSUMS](https://docs.pulpproject.org/pulpcore/settings.html#allowed-content-checksums). I assume this is an issue on rh-repo side, not pulp or pulp.squeezer related.

```
The full traceback is:
Traceback (most recent call last):

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeezer/plugins/modules/rpm_remote.py", line 131, in main

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/pulp.py", line 241, in process
    self.update()

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/pulp.py", line 195, in update
    self._update_id, parameters=self.primary_key, body=self.entity

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible_collections/pulp/squeezer/plugins/module_utils/openapi.py", line 253, in call
    method, url, data=data, headers=headers, unix_socket=self.unix_socket

  File "/tmp/ansible_pulp.squeezer.rpm_remote_payload_u3ygza6q/ansible_pulp.squeezer.rpm_remote_payload.zip/ansible/module_utils/urls.py", line 1304, in open
    return urllib_request.urlopen(request, None, timeout)

  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)

  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)

  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)

  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)

  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)

  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

urllib.error.HTTPError: HTTP Error 400: Bad Request
fatal: [pulp]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_cert": "-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----\n",
            "client_cert": "-----BEGIN CERTIFICATE------...-----END CERTIFICATE-----\n-----BEGIN ENTITLEMENT DATA-----...-----END ENTITLEMENT DATA-----\n-----BEGIN RSA SIGNATURE-----...-----END RSA SIGNATURE-----\n",
            "client_key": "-----BEGIN RSA PRIVATE KEY-----...-----END RSA PRIVATE KEY-----\n",
            "download_concurrency": null,
            "name": "rhel-7-server-rpms",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "policy": null,
            "proxy_password": null,
            "proxy_username": null,
            "pulp_url": "http://localhost:8080",
            "refresh_api_cache": false,
            "remote_password": null,
            "remote_username": null,
            "state": "present",
            "tls_validation": null,
            "url": "https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os",
            "username": "admin",
            "validate_certs": true
        }
    },
    "msg": "HTTP Error 400: Bad Request"
}
```

```
$ podman logs --tail pulp
...output omitted...
pulp [bc136f6661ae457093d0e34440df4fc7]: django.request:WARNING: Bad Request: /pulp/api/v3/remotes/rpm/rpm/cabf838f-9f29-49f0-ac0c-60573b0a1800/
```

Should I use latest container image of pulp or is 3.12 ok? Iatest seems to be broken, I wasn't able to connect to the pulp api.

Idempotence: I assume the task result is always `changed: true` while using the  `client_key` option. What about an extra option called something like `client_auth_update: yes/no`? Or add an example on how to check if remote repo exists and then omit the `client_key` option.

Let me know if I can help you further with testing, I'm happy to help!

**Comment by keilr** [comment]
@mdellweg: how could we handle the HTTP 400 error? is there a possible workaround in the ansible module or is the problem on pulp rpm API level?

**Comment by mdellweg** [comment]
Sorry, for the delay. I needed to fix the ci in the meantime...
I will try to get back at this soon.

**Comment by mdellweg** [comment]
> @mdellweg: how could we handle the HTTP 400 error? is there a possible workaround in the ansible module or is the problem on pulp rpm API level?

We should at least have better reporting of 400 errors.
Maybe this really comes down to idempotence issues.

**Comment by mdellweg** [comment]
I get the bad request even without this patch. It's the old api recordings that do not experience this.
Needs further investigation.

**Comment by mdellweg** [comment]
The bad request should be solved by #67

**Comment by mdellweg** [comment]
@keilr would you mind to test again?

**Comment by mdellweg** [comment]
> Idempotence: I assume the task result is always `changed: true` while using the `client_key` option. What about an extra option called something like `client_auth_update: yes/no`? Or add an example on how to check if remote repo exists and then omit the `client_key` option.

@keilr Yes, they will always report changed. And quite frankly they will always be overwritten too (which is what you expect a playbook to do for you). What you can do is, you can rebuild the idempotence in ansible:
1. query for the remote (without `state`)
2. `state=present` the remote with creds only if not existant

You can combine the `ternary` filter with `omit` to this end.

If however you want to set the creds as specified, but let the playbook report changed as good as possible, i'd go for:
1. `state=present` the remote without creds
2. `state=present` the remote with creds and `changed_when: falss`

**Pull request merged**
